deploy:
	cd draw; fn deploy myapp
	cd publish; fn deploy myapp
	cd detect-plates; fn deploy myapp
	cd detect-faces; fn deploy myapp
	cd alert; fn deploy myapp
	cd scraper; fn deploy myapp
	cd split-video; fn deploy myapp

deploy-local:
	cd flow; fn deploy --local --app myapp
	cd draw; fn deploy --local --app myapp
	cd detect-plates; fn deploy --local --app myapp
	cd alert; fn deploy --local --app myapp
	cd scraper; fn deploy --local --app myapp
